### ISSUE TITLE
`Disputes` object is not currently supported

### ISSUE THREAD

**Issue by dylan-stitch** [singer-io/tap-stripe#18]
There's a native `disputes` object available from Stripe that could likely have incremental updates detected based on the Events object just as others are.

https://stripe.com/docs/api/disputes/object

This would provide users with more thorough insight into disputes against charges.

**Comment by timvisher** [comment]
To get this data I think we'd want to:

1. Add `disputes` to the `STREAM_SDK_OBJECTS` dict [here](https://github.com/singer-io/tap-stripe/blob/2cdb36d898df47bb675ebcc71072bcbf1f8e886d/tap_stripe/__init__.py#L32)
1. Add `disputes` to the `STREAM_REPLICATION_KEY ` dict [here](https://github.com/singer-io/tap-stripe/blob/2cdb36d898df47bb675ebcc71072bcbf1f8e886d/tap_stripe/__init__.py#L35) with the proper replication key (it doesn't appear to be a substream).
1. Get a schema generated for it.
1. Do some test runs.

The trickiest bit is likely to be getting the schema right.

PRs welcome!

**Comment by cmerrick** [comment]
To elaborate on the test strategy here, start by adding the new stream to https://github.com/stitchdata/tap-tester/blob/master/tap_tester/suites/stripe/base.py#L96-L111 with correct (incremental) metadata and getting tests to pass
