### ISSUE TITLE
Products resource is not available

### ISSUE THREAD

**Issue by daniellangnet** [singer-io/tap-stripe#21]
Stripe has migrated to products and plans over a year ago with API version `2018-02-05` ([see here](https://stripe.com/docs/billing/migration/products-and-plans)).

Currently the `products` resource is not being loaded, which means that for any company that has more than one product available and uses the Stripe recommended way of modeling products and plans, it is currently not possible to do any per-product analysis, without loading the product table into the warehouse by other means.

I'm new to Singer/Stitch and don't know Python, otherwise I'd be happy to help.

**Comment by cmerrick** [comment]
Here's how to go about adding this data set:

1. Add `products` to the STREAM_SDK_OBJECTS dict
2. Add `products` to the STREAM_REPLICATION_KEY dict with `created` as its replication key
3. Add `products` to the STREAM_TO_TYPE_FILTER dict with `type` of `product.*` and object of `product`
4. Generate schemas
5. Write tests by adding the new stream to https://github.com/stitchdata/tap-tester/blob/master/tap_tester/suites/stripe/base.py#L96-L111 with correct (incremental) metadata and getting tests to pass. Add another test that syncs data, then adds, updates, and deletes `products` through the stripe API, syncs data again, and ensures all of the changes (and only the changes) are captured

**Comment by aiguofer** [comment]
I've started work on this. One thing I noticed is that the `Products` object actually has an[ `updated` field](https://stripe.com/docs/api/products/object#product_object-updated), unlike almost every other Stripe object. I'm wondering how this will conflict with the auto-generated `updated` field?

**Comment by aiguofer** [comment]
Stepping through the code, I see that on initial sync, the `updated` field will get overridden with the `created` timestamp like the other streams. However, whenever it's syncing updates from the `events` stream, it sets the `updated` field to the `created` date of the `event` object. When looking at a few examples while stepping through the code, it seems like these always match anyway.

That being the case, I don't think we need any other changes regarding that field. Thoughts?

**Comment by cmerrick** [comment]
I agree with your assessment - that sounds like behavior that won’t cause challenges or problems


________________________________

**Comment by aiguofer** [comment]
Great. I added this to the new EventUpdatesTest. Do you think that's
enough, or should I create a test for creates and deletes as well (and make
them generic for other streams)?
